// Typed fetch wrapper for the FastAPI backend.
//
// Uses paths from @voiceqa/shared-types (regenerated by `make codegen`; a
// placeholder until then). Server components forward the auth cookie via
// cookies() from next/headers; in the browser, `credentials: "include"`
// covers it.

import type { paths } from "@voiceqa/shared-types";

type ApiResponse<P extends keyof paths, M extends keyof paths[P]> = paths[P][M] extends {
  responses: { 200: { content: { "application/json": infer R } } };
}
  ? R
  : never;

// Server components call the backend directly; the browser calls same-origin
// ("" base) and next.config's rewrite proxies /api/* to the backend — so the
// session cookie is first-party (no cross-site SameSite/CORS problems).
export const API_URL =
  typeof window === "undefined"
    ? process.env.BACKEND_API_URL ?? process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:7870"
    : (process.env.NEXT_PUBLIC_API_URL ?? "");

export class ApiError extends Error {
  constructor(public status: number, public body: unknown, message?: string) {
    super(message ?? `API ${status}`);
    this.name = "ApiError";
  }
}

export interface ApiOptions {
  // Server components must pass the cookie header explicitly.
  cookieHeader?: string;
  signal?: AbortSignal;
  body?: unknown;
  // Path params for templated paths like /api/batches/{batch_id}.
  // Query params get appended as ?k=v; nullish values are skipped.
  params?: {
    path?: Record<string, string>;
    query?: Record<string, string | number | boolean | undefined | null>;
  };
}

export async function apiCall<P extends keyof paths, M extends keyof paths[P] & string>(
  path: P,
  method: M,
  opts: ApiOptions = {},
): Promise<ApiResponse<P, M>> {
  const headers: Record<string, string> = {
    "Content-Type": "application/json",
  };
  if (opts.cookieHeader) headers["Cookie"] = opts.cookieHeader;

  let url = String(path);
  if (opts.params?.path) {
    for (const [key, value] of Object.entries(opts.params.path)) {
      url = url.replace(`{${key}}`, encodeURIComponent(value));
    }
  }
  if (opts.params?.query) {
    const qs = new URLSearchParams();
    for (const [k, v] of Object.entries(opts.params.query)) {
      if (v == null) continue;
      qs.set(k, String(v));
    }
    const s = qs.toString();
    if (s) url += `?${s}`;
  }

  const res = await fetch(`${API_URL}${url}`, {
    method: method.toUpperCase(),
    headers,
    body: opts.body !== undefined ? JSON.stringify(opts.body) : undefined,
    credentials: "include",
    signal: opts.signal,
    cache: "no-store",
  });

  const text = await res.text();
  let parsed: unknown = undefined;
  if (text.length > 0) {
    try {
      parsed = JSON.parse(text);
    } catch {
      parsed = text;
    }
  }

  if (!res.ok) {
    throw new ApiError(res.status, parsed);
  }

  return parsed as ApiResponse<P, M>;
}

/**
 * Human-readable message out of an ApiError. FastAPI errors are either
 * `{detail: "..."}` or `{detail: [{loc, msg, ...}, ...]}` (422 validation).
 */
export function getApiErrorMessage(e: unknown): string {
  if (e instanceof ApiError) {
    const detail =
      e.body !== null && typeof e.body === "object" && "detail" in e.body
        ? (e.body as { detail: unknown }).detail
        : undefined;
    if (typeof detail === "string") return detail;
    if (Array.isArray(detail)) {
      const msgs = detail
        .map((d) => {
          if (d !== null && typeof d === "object" && "msg" in d) {
            const item = d as { msg: unknown; loc?: unknown };
            const loc = Array.isArray(item.loc)
              ? item.loc.filter((p) => p !== "body" && p !== "query").join(".")
              : "";
            return loc ? `${loc}: ${String(item.msg)}` : String(item.msg);
          }
          return JSON.stringify(d);
        })
        .join("; ");
      if (msgs) return msgs;
    }
    return `Request failed (HTTP ${e.status})`;
  }
  if (e instanceof Error) return e.message;
  return "Something went wrong";
}

export interface UploadOptions {
  /** Upload progress in [0, 1]. */
  onProgress?: (fraction: number) => void;
  signal?: AbortSignal;
  /** Extra multipart form fields sent alongside `file`. */
  fields?: Record<string, string>;
}

/**
 * Multipart POST (single field named `file`) via XHR — fetch() has no upload
 * progress events. Browser-only. Cookies ride along via withCredentials,
 * mirroring apiCall's `credentials: "include"`.
 */
export function uploadMultipart<T>(
  path: string,
  file: File,
  opts: UploadOptions = {},
): Promise<T> {
  return new Promise<T>((resolve, reject) => {
    const xhr = new XMLHttpRequest();
    xhr.open("POST", `${API_URL}${path}`);
    xhr.withCredentials = true;

    if (opts.onProgress) {
      xhr.upload.onprogress = (ev) => {
        if (ev.lengthComputable && ev.total > 0) opts.onProgress!(ev.loaded / ev.total);
      };
    }

    const onAbort = () => xhr.abort();
    opts.signal?.addEventListener("abort", onAbort);

    xhr.onload = () => {
      opts.signal?.removeEventListener("abort", onAbort);
      let parsed: unknown;
      try {
        parsed = xhr.responseText ? JSON.parse(xhr.responseText) : undefined;
      } catch {
        parsed = xhr.responseText;
      }
      if (xhr.status >= 200 && xhr.status < 300) {
        resolve(parsed as T);
      } else {
        reject(new ApiError(xhr.status, parsed));
      }
    };
    xhr.onerror = () => {
      opts.signal?.removeEventListener("abort", onAbort);
      reject(new ApiError(0, null, "Network error during upload"));
    };
    xhr.onabort = () => {
      opts.signal?.removeEventListener("abort", onAbort);
      reject(new ApiError(0, null, "Upload cancelled"));
    };

    const form = new FormData();
    for (const [k, v] of Object.entries(opts.fields ?? {})) form.append(k, v);
    form.append("file", file);
    xhr.send(form);
  });
}
